#!/usr/bin/env npx tsx
/**
 * Docs fetcher — runs at build time to pull official documentation
 * and save condensed versions as knowledge files.
 *
 * Usage: npx tsx scripts/fetch-docs.ts [stack]
 *   npx tsx scripts/fetch-docs.ts          # fetch all
 *   npx tsx scripts/fetch-docs.ts nextjs   # fetch only Next.js
 *
 * Each stack defines a list of doc URLs and a transform function
 * that extracts the useful parts. Output goes to knowledge/{stack}/docs.md
 */

import { writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'

const KNOWLEDGE_DIR = join(import.meta.dirname, '..', 'knowledge')

interface DocSource {
  url: string
  label: string
}

interface StackDocs {
  name: string
  sources: DocSource[]
  transform: (responses: { label: string; text: string }[]) => string
}

async function fetchPage(url: string): Promise<string> {
  try {
    const res = await fetch(url, {
      headers: { 'User-Agent': 'codebase-lens-docs-fetcher/0.1' },
    })
    if (!res.ok) return `[Failed to fetch: ${res.status}]`
    return await res.text()
  } catch (err: any) {
    return `[Fetch error: ${err.message}]`
  }
}

function extractTextFromHtml(html: string): string {
  // Strip HTML tags, decode common entities, collapse whitespace
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, '')
    .replace(/<style[\s\S]*?<\/style>/gi, '')
    .replace(/<nav[\s\S]*?<\/nav>/gi, '')
    .replace(/<footer[\s\S]*?<\/footer>/gi, '')
    .replace(/<header[\s\S]*?<\/header>/gi, '')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 15000) // Cap at ~15KB per page to keep knowledge files manageable
}

// ---------------------------------------------------------------------------
// Stack doc definitions
// ---------------------------------------------------------------------------

const NEXT_JS_DOCS: StackDocs = {
  name: 'nextjs',
  sources: [
    { url: 'https://nextjs.org/docs/app/getting-started/project-structure', label: 'Project Structure' },
    { url: 'https://nextjs.org/docs/app/building-your-application/routing', label: 'Routing' },
    { url: 'https://nextjs.org/docs/app/building-your-application/data-fetching', label: 'Data Fetching' },
    { url: 'https://nextjs.org/docs/app/building-your-application/rendering', label: 'Rendering' },
    { url: 'https://nextjs.org/docs/app/api-reference/next-config-js', label: 'next.config.js' },
    { url: 'https://nextjs.org/docs/app/building-your-application/configuring/environment-variables', label: 'Environment Variables' },
  ],
  transform(responses) {
    const header = `# Next.js Documentation (auto-fetched)\n\nFetched: ${new Date().toISOString().split('T')[0]}\n\nThis file is auto-generated by \`scripts/fetch-docs.ts\`. Do not edit manually.\nFor community-maintained best practices, see \`community.md\` in this directory.\n\n`

    const sections = responses.map(r => {
      const text = extractTextFromHtml(r.text)
      return `## ${r.label}\n\n${text}\n`
    })

    return header + sections.join('\n---\n\n')
  },
}

const ALL_STACKS: StackDocs[] = [NEXT_JS_DOCS]

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function fetchStack(stack: StackDocs): Promise<void> {
  console.log(`\n📚 Fetching ${stack.name} docs (${stack.sources.length} pages)...`)

  const responses: { label: string; text: string }[] = []
  for (const source of stack.sources) {
    process.stdout.write(`  → ${source.label}...`)
    const text = await fetchPage(source.url)
    responses.push({ label: source.label, text })
    console.log(` ${Math.round(text.length / 1024)}KB`)
  }

  const output = stack.transform(responses)
  const outDir = join(KNOWLEDGE_DIR, stack.name)
  mkdirSync(outDir, { recursive: true })
  const outPath = join(outDir, 'docs.md')
  writeFileSync(outPath, output)
  console.log(`  ✓ Wrote ${outPath} (${Math.round(output.length / 1024)}KB)`)
}

const targetStack = process.argv[2]

if (targetStack) {
  const stack = ALL_STACKS.find(s => s.name === targetStack)
  if (!stack) {
    console.error(`Unknown stack: ${targetStack}. Available: ${ALL_STACKS.map(s => s.name).join(', ')}`)
    process.exit(1)
  }
  await fetchStack(stack)
} else {
  for (const stack of ALL_STACKS) {
    await fetchStack(stack)
  }
}

console.log('\n✅ Done. Knowledge files updated.')
