#!/usr/bin/env npx tsx
/**
 * Docs fetcher: pulls a curated set of official Next.js docs pages into knowledge/nextjs/docs/.
 *
 * nextjs.org serves every docs page as Markdown when `.md` is appended to its URL, so no HTML scraping is needed.
 * Each page becomes its own file (and its own MCP resource) plus an index, so Claude reads only the page a question
 * needs instead of one large dump.
 *
 * Usage: npm run fetch-docs
 *
 * All pages are fetched before anything is written, so a failed run leaves the existing docs untouched.
 */

import { existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const OUT_DIR = join(import.meta.dirname, '..', 'knowledge', 'nextjs', 'docs')
const DOCS_BASE = 'https://nextjs.org/docs/app/'
const USER_AGENT = 'nextjs-lens-docs-fetcher'

// Pages behind nextjs-lens's tools, grouped by what they inform
const PAGES: { path: string; topic: string }[] = [
  { path: 'getting-started/project-structure', topic: 'Routing and file conventions' },
  { path: 'getting-started/layouts-and-pages', topic: 'Routing and file conventions' },
  { path: 'api-reference/file-conventions/parallel-routes', topic: 'Routing and file conventions' },
  { path: 'api-reference/file-conventions/route-segment-config', topic: 'Routing and file conventions' },
  { path: 'getting-started/server-and-client-components', topic: 'Server and Client Components' },
  { path: 'getting-started/route-handlers', topic: 'Route handlers, proxy, and security' },
  { path: 'getting-started/proxy', topic: 'Route handlers, proxy, and security' },
  { path: 'guides/data-security', topic: 'Route handlers, proxy, and security' },
  { path: 'api-reference/config/next-config-js/serverActions', topic: 'Route handlers, proxy, and security' },
  { path: 'getting-started/fetching-data', topic: 'Data fetching and caching' },
  { path: 'getting-started/caching', topic: 'Data fetching and caching' },
  { path: 'guides/caching-without-cache-components', topic: 'Data fetching and caching' },
  { path: 'guides/environment-variables', topic: 'Configuration' },
  { path: 'guides/upgrading/version-16', topic: 'Upgrading' },
]

interface Page {
  path: string
  topic: string
  file: string
  title: string
  description: string
  url: string
  body: string
}

async function fetchText(url: string): Promise<string> {
  const res = await fetch(url, { headers: { 'User-Agent': USER_AGENT } })
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`)
  return res.text()
}

/** Split the YAML-ish frontmatter nextjs.org puts on Markdown pages from the body. */
function parsePage(markdown: string, fallbackUrl: string): { title: string; description: string; url: string; body: string } {
  const match = markdown.match(/^---\n([\s\S]*?)\n---\n/)
  const front = match?.[1] ?? ''
  const field = (name: string) => front.match(new RegExp(`^${name}:\\s*"?(.+?)"?\\s*$`, 'm'))?.[1] ?? ''
  const body = markdown
    .slice(match ? match[0].length : 0)
    // Every page repeats a pointer to the site-wide index; the generated index replaces it
    .replace(/^> For an index of all Next\.js documentation, see .*\n/m, '')
    // Site-relative links are dead ends outside nextjs.org
    .replace(/\]\(\/docs\//g, '](https://nextjs.org/docs/')
    .trim()
  return { title: field('title'), description: field('description'), url: field('url') || fallbackUrl, body }
}

async function main(): Promise<void> {
  console.log(`Fetching ${PAGES.length} Next.js docs pages as Markdown…`)

  const index = await fetchText('https://nextjs.org/docs/llms.txt')
  const version = index.match(/Next\.js (\d+\.\d+\.\d+)/)?.[1] ?? 'unknown'

  const pages: Page[] = []
  for (const { path, topic } of PAGES) {
    const url = `${DOCS_BASE}${path}`
    const parsed = parsePage(await fetchText(`${url}.md`), url)
    const file = `${path.split('/').pop()}.md`
    if (pages.some(p => p.file === file)) throw new Error(`Two pages would both be written to ${file}`)
    pages.push({ path, topic, file, ...parsed })
    console.log(`  ✓ ${path} (${Math.round(parsed.body.length / 1024)} KB)`)
  }

  const fetched = new Date().toISOString().split('T')[0]
  if (existsSync(OUT_DIR)) rmSync(OUT_DIR, { recursive: true })
  mkdirSync(OUT_DIR, { recursive: true })

  for (const page of pages) {
    const header =
      `<!-- Auto-generated by scripts/fetch-docs.ts from ${page.url} (Next.js ${version}, fetched ${fetched}). Do not edit. -->\n\n` +
      `# ${page.title}\n\n> ${page.description}\n>\n> Source: ${page.url}\n\n`
    writeFileSync(join(OUT_DIR, page.file), header + page.body + '\n')
  }

  const topics = [...new Set(pages.map(p => p.topic))]
  const indexMd =
    `<!-- Auto-generated by scripts/fetch-docs.ts. Do not edit. -->\n\n` +
    `# Next.js documentation (selected pages)\n\n` +
    `Official Next.js ${version} docs, fetched ${fetched}. Each page is a separate resource; read only the ones a question needs.\n` +
    `For patterns and gotchas the docs don't cover, see \`lens://knowledge/nextjs/community.md\`.\n\n` +
    topics.map(topic =>
      `## ${topic}\n\n` +
      pages.filter(p => p.topic === topic).map(p => `- [${p.title}](lens://knowledge/nextjs/docs/${p.file}): ${p.description}`).join('\n'),
    ).join('\n\n') + '\n'
  writeFileSync(join(OUT_DIR, 'index.md'), indexMd)

  const totalKb = Math.round(pages.reduce((sum, p) => sum + p.body.length, 0) / 1024)
  console.log(`Wrote ${pages.length} pages + index.md to ${OUT_DIR} (${totalKb} KB, Next.js ${version})`)
}

main().catch(err => {
  console.error(`Docs fetch failed; existing docs left untouched.\n${err.message}`)
  process.exit(1)
})
